title: S. Solomon Darnell's Biological Intelligent Research
description: Merging AI, Affect, Human Centered Computing and Identity with Genetics and Genomics
show_downloads: false
google_analytics: false
theme: jekyll-theme-modernist